# Generated by Django 5.0.4 on 2024-05-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0003_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='age',
        ),
        migrations.AddField(
            model_name='myuser',
            name='contacts',
            field=models.ManyToManyField(to='chat_api.myuser'),
        ),
    ]
