# Generated by Django 5.0.4 on 2024-05-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0004_remove_myuser_age_myuser_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='chat_api.myuser'),
        ),
    ]
