# Generated by Django 5.0.4 on 2024-05-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0006_remove_myuser_contacts_remove_myuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='chat_api.myuser'),
        ),
    ]
