# Generated by Django 5.0.4 on 2024-05-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0009_message_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_api.myuser'),
        ),
    ]
