# Generated by Django 5.0.4 on 2024-05-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0010_alter_message_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remitentes', to='chat_api.myuser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='chat_api.myuser'),
        ),
    ]
